baseURL = "https://karanrai13.github.io/"
title = "CodeCrux | Portfolio & Blog"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  defaultTheme = "auto"
  enableSRI = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "ğŸ  Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "portfolio"
    name = "ğŸ’¼ Portfolio"
    url = "/portfolio/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "âœï¸ Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "ğŸ“¬ Contact"
    url = "/contact/"
    weight = 4
